version: "3.8"
services:
    backend:
        image: nestjs-dev
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
            target: local
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        networks:
            - backend
        depends_on:
            - rdb
        command: nest start --watch 
    rdb:
        image: postgres
        restart: always
        volumes:
            - rdb-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - backend
volumes: 
    rdb-data:
        driver: local
networks: 
    backend: