version: "3.8"
services:
    proxy:
        image: nginx
        restart: always
        volumes:
            - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/proxy/conf.d:/etc/nginx/conf.d
            - ./docker/proxy/log:/var/log/nginx
            - ./auth:/var/www/auth
        ports:
            - "80:80"
        depends_on:
            - backend
            - auth
    auth:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/auth/Dockerfile
        expose:
            - "9000"
        volumes:
            - ./auth:/var/www/auth
    backend:
        image: nestjs-dev
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
            target: local
        volumes:
            - ./backend:/app
            - /app/node_modules
        expose:
            - "3000"
        depends_on:
            - rdb
        command: nest start --watch 
    rdb:
        image: postgres
        restart: always
        volumes:
            - rdb-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
volumes:
    rdb-data:
        driver: local
